// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb6PDU2Re3G9JlkBiODk2n8VEZ68WMD28',
    appId: '1:1050515848109:web:97c15cecd2b796c895ff24',
    messagingSenderId: '1050515848109',
    projectId: 'prayer-times-e5083',
    authDomain: 'prayer-times-e5083.firebaseapp.com',
    storageBucket: 'prayer-times-e5083.firebasestorage.app',
    measurementId: 'G-DQXWRP4CBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDls8AzfFq5edviqVHAXHjarh6OO4VlL0U',
    appId: '1:1050515848109:android:ff04c2f6533254d095ff24',
    messagingSenderId: '1050515848109',
    projectId: 'prayer-times-e5083',
    storageBucket: 'prayer-times-e5083.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt977OHWtJsjIMQlFy_R-Dea09-liUh90',
    appId: '1:1050515848109:ios:82786de4e9d1a8c495ff24',
    messagingSenderId: '1050515848109',
    projectId: 'prayer-times-e5083',
    storageBucket: 'prayer-times-e5083.firebasestorage.app',
    iosBundleId: 'com.oratiq.prayerTimes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt977OHWtJsjIMQlFy_R-Dea09-liUh90',
    appId: '1:1050515848109:ios:82786de4e9d1a8c495ff24',
    messagingSenderId: '1050515848109',
    projectId: 'prayer-times-e5083',
    storageBucket: 'prayer-times-e5083.firebasestorage.app',
    iosBundleId: 'com.oratiq.prayerTimes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb6PDU2Re3G9JlkBiODk2n8VEZ68WMD28',
    appId: '1:1050515848109:web:8733cf0340cc807495ff24',
    messagingSenderId: '1050515848109',
    projectId: 'prayer-times-e5083',
    authDomain: 'prayer-times-e5083.firebaseapp.com',
    storageBucket: 'prayer-times-e5083.firebasestorage.app',
    measurementId: 'G-1EQ3YCZDRP',
  );
}
